/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef FIRSTBINPDF
#define FIRSTBINPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class firstbinpdf : public RooAbsPdf {
public:
  firstbinpdf() {} ; 
  firstbinpdf(const char *name, const char *title,
	      RooAbsReal& _roovar);
  firstbinpdf(const firstbinpdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new firstbinpdf(*this,newname); }
  inline virtual ~firstbinpdf() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooRealProxy roovar ;
  
  Double_t evaluate() const ;

private:

  ClassDef(firstbinpdf,1) // Your description goes here...
};
 
#endif
